[X1 Y1] = loadPrecisionRecall('./zished/experiments/felzenszwalb.dat');
[X2 Y2] = loadPrecisionRecall('./zished/experiments/threshold.dat');
[X3 Y3] = loadPrecisionRecall('./zished/experiments/linear.dat');
[X4 Y4] = loadPrecisionRecall('./zished/experiments/square.dat');


%CREATEFIGURE(X1, Y1, X2, Y2, X3, Y3, X4, Y4)
%  X1:  vector of x data
%  Y1:  vector of y data
%  X2:  vector of x data
%  Y2:  vector of y data
%  X3:  vector of x data
%  Y3:  vector of y data
%  X4:  vector of x data
%  Y4:  vector of y data

%  Auto-generated by MATLAB on 05-Mar-2015 19:39:57

% Create figure
figure1 = figure;

% Create axes
axes1 = axes('Parent',figure1,'YGrid','on','XGrid','on',...
    'Color',[0.831372559070587 0.815686285495758 0.7843137383461],...
    'ZColor',[1 1 1],...
    'YColor',[0 0 0],...
    'XColor',[0 0 0],...
    'FontSize',16,...
    'Position',[0.13 0.11 0.688181818181818 0.815]);
%% Uncomment the following line to preserve the Y-limits of the axes
% ylim(axes1,[0.5 1.02]);
box(axes1,'on');
hold(axes1,'on');

% Create ylabel
ylabel('Rand merge score','FontSize',16);

% Create xlabel
xlabel('Rand split score','FontSize',16);

% Create plot
plot(X1,Y1,'DisplayName','Felzenszwalb','MarkerSize',8,'Marker','square',...
    'LineWidth',2);

% Create plot
plot(X2,Y2,'DisplayName','\tau(s) = k','MarkerSize',8,'Marker','diamond',...
    'LineWidth',2,...
    'Color',[0 0.447058826684952 0.74117648601532]);

% Create plot
plot(X3,Y3,'DisplayName','\tau^{-1}(w)=kw','MarkerSize',8,'Marker','^',...
    'LineWidth',2);

% Create plot
plot(X4,Y4,'DisplayName','\tau^{-1}(w) = kw^2','MarkerSize',8,'Marker','o',...
    'LineWidth',2);

% Create legend
legend1 = legend(axes1,'show');
set(legend1,...
    'Position',[0.824432114109849 0.684210526315789 0.168295158617424 0.240601473905362],...
    'EdgeColor',[1 1 1],...
    'Color',[1 1 1]);

